export const initializeApp = jest.fn();
export const getFirestore = jest.fn();
export const getAuth = jest.fn(() => ({ currentUser: null }));
export const updateProfile = jest.fn();
export const createUserWithEmailAndPassword = jest.fn();
export const signInWithEmailAndPassword = jest.fn();
export const signInWithRedirect = jest.fn();
export const GoogleAuthProvider = jest.fn();
export const signOut = jest.fn();
export const onAuthStateChanged = jest.fn();
